name: lint-yaml

on:
  pull_request:
    paths:
      - '*.yaml'

jobs:
  lint:
    name: Lint YAML Files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'
          bundler-cache: true
          working-directory: ./scripts

      - name: Check YAML normalization
        id: check_yaml
        working-directory: ./scripts
        run: |
          bundle exec unitsdb-utils normalize --all --dir ..

      - name: Check field uniqueness
        id: check_uniqueness
        working-directory: ./scripts
        run: |
          bundle exec unitsdb-utils check_uniqueness --all --dir ..

      - name: Comment on Normalization Issues
        if: failure() && steps.check_yaml.outputs.issues_found == 'true'
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ## YAML Normalization Required

            The following YAML files need to be normalized:
            ${{ steps.check_yaml.outputs.issue_details }}

            Please run the normalization script before submitting your PR:

            ```bash
            cd scripts
            bundle install
            bundle exec unitsdb-utils normalize --all --dir ..
            ```

            See the [contribution guidelines](../blob/main/README.adoc#contributing) for more information.
          reactions: 'eyes'

      - name: Comment on Uniqueness Issues
        if: failure() && steps.check_uniqueness.outputs.uniqueness_issues_found == 'true'
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ## Duplicate Fields Found

            The YAML files contain duplicate field identifiers:

            ```
            ${{ steps.check_uniqueness.outputs.uniqueness_details }}
            ```

            Please ensure all 'short' and 'id' fields are unique within each object type.
            You can check for duplicates by running:

            ```bash
            cd scripts
            bundle install
            bundle exec unitsdb-utils check_uniqueness --all --dir ..
            ```

            See the [contribution guidelines](../blob/main/README.adoc#contributing) for more information.
          reactions: 'eyes'
