name: lint-yaml

on:
  pull_request:
    paths:
      - '*.yaml'

jobs:
  lint:
    name: Check YAML Normalization
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'
          bundler-cache: true
          working-directory: ./scripts

      - name: Check YAML normalization
        id: check_yaml
        run: |
          set -e

          # Run the normalization script
          cd scripts
          bundle exec unitsdb-utils normalize --all --dir ..
          cd ..

          # Check if there are any changes
          if [[ -n "$(git status --porcelain)" ]]; then
            echo "::warning::YAML files are not properly normalized"
            echo "issues_found=true" >> $GITHUB_OUTPUT

            # Get list of modified files
            MODIFIED_FILES=$(git status --porcelain | grep '^ M' | awk '{print $2}' | grep '\.yaml$')

            # Create issue details
            ISSUE_DETAILS=""
            for file in $MODIFIED_FILES; do
              echo "::warning file=$file::YAML file is not properly normalized"
              ISSUE_DETAILS+="- $file is not properly normalized\n"
              # Show diff for debugging
              git diff $file
            done

            echo "issue_details<<EOF" >> $GITHUB_OUTPUT
            echo -e "$ISSUE_DETAILS" >> $GITHUB_OUTPUT
            echo "EOF" >> $GITHUB_OUTPUT

            # Reset changes to avoid affecting other steps
            git reset --hard

            exit 1
          else
            echo "All YAML files are properly normalized!"
          fi

      - name: Comment on PR
        if: failure() && steps.check_yaml.outputs.issues_found == 'true'
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issueDetails = `${{ steps.check_yaml.outputs.issue_details }}`;

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `## YAML Normalization Required

            The following YAML files need to be normalized:
            ${issueDetails}

            Please run the normalization script before submitting your PR:

            ```bash
            cd scripts
            bundle install
            bundle exec unitsdb-utils normalize --all --dir ..
            ```

            See the [contribution guidelines](../blob/main/README.adoc#contributing) for more information.`
            });
