name: release

on:
  push:
    tags:
    - "v*.*.*"


permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.3'
        bundler-cache: true

    - name: Install unitsdb gem
      run: gem install unitsdb

    - name: Extract tag version
      id: get_version
      run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

    - name: Create release directory
      run: mkdir -p release

    - name: Generate release files
      run: |
        unitsdb release --database=. --output-dir=release --version=$VERSION

    - name: Create GitHub Release
      id: create_release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          release/unitsdb-${{ env.VERSION }}.yaml
          release/unitsdb-${{ env.VERSION }}.zip
        draft: false
        prerelease: false
        generate_release_notes: true
