name: validate

on:
  push:
    branches: [ main ]
    tags: [ v* ]
    paths:
      - '*.yaml'
  pull_request:
    paths:
      - '*.yaml'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'
          bundler-cache: true

      - name: Install unitsdb gem
        run: gem install unitsdb

      - name: Validate identifiers
        run: unitsdb validate identifiers --database=.

      - name: Validate references
        run: unitsdb validate references --database=.

      - name: Validate SI references
        run: unitsdb validate si_references --database=.
