name: validate

on:
  push:
    branches: [ main ]
    tags: [ v* ]
    paths:
      - '*.yaml'
      - 'spec/**/*'
  pull_request:
    paths:
      - '*.yaml'
      - 'spec/**/*'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'
          bundler-cache: true
          working-directory: ./scripts

      - name: Run tests
        working-directory: ./scripts
        run: bundle exec rspec ../spec --format documentation

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: rspec-results
          path: scripts/tmp/rspec_results.html
          if-no-files-found: ignore